name: Release

# Run this workflow every time a new tag pushed to your repository
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'           # Push events to every tag


jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
#      - run: yarn build
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}